### ISSUE TITLE
readSMS Not working... "'uint8_t index' redeclared as different kind of symbol"

### ISSUE THREAD

**Issue by paulpenney** [cristiansteib/Sim800l#11]
When I try and run readSMS, I am returned with "'uint8_t index' redeclared as different kind of symbol"

//

Arduino: 1.6.9 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 160 MHz, 115200, 4M (3M SPIFFS)"

/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware "/Applications/Arduino.app/Contents/Java/hardware" -hardware "/Users/paulpenney/Library/Arduino15/packages" -tools "/Applications/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino.app/Contents/Java/hardware/tools/avr" -tools "/Users/paulpenney/Library/Arduino15/packages" -built-in-libraries "/Applications/Arduino.app/Contents/Java/libraries" -libraries "/Users/paulpenney/Documents/Arduino/libraries" -fqbn=esp8266:esp8266:nodemcuv2:CpuFrequency=160,UploadSpeed=115200,FlashSize=4M3M -ide-version=10609 -build-path "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/arduino_modified_sketch_910342/readSms.ino"
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware "/Applications/Arduino.app/Contents/Java/hardware" -hardware "/Users/paulpenney/Library/Arduino15/packages" -tools "/Applications/Arduino.app/Contents/Java/tools-builder" -tools "/Applications/Arduino.app/Contents/Java/hardware/tools/avr" -tools "/Users/paulpenney/Library/Arduino15/packages" -built-in-libraries "/Applications/Arduino.app/Contents/Java/libraries" -libraries "/Users/paulpenney/Documents/Arduino/libraries" -fqbn=esp8266:esp8266:nodemcuv2:CpuFrequency=160,UploadSpeed=115200,FlashSize=4M3M -ide-version=10609 -build-path "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp" -warnings=none -prefs=build.warn_data_percentage=75 -verbose "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/arduino_modified_sketch_910342/readSms.ino"
"/Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=160000000L -DLWIP_OPEN_SRC   -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/sketch/readSms.ino.cpp" -o "/dev/null"
"/Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=160000000L -DLWIP_OPEN_SRC   -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "-I/Users/paulpenney/Documents/Arduino/libraries/Sim800l" "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/sketch/readSms.ino.cpp" -o "/dev/null"
"/Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=160000000L -DLWIP_OPEN_SRC   -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "-I/Users/paulpenney/Documents/Arduino/libraries/Sim800l" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SoftwareSerial" "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/sketch/readSms.ino.cpp" -o "/dev/null"
"/Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=160000000L -DLWIP_OPEN_SRC   -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "-I/Users/paulpenney/Documents/Arduino/libraries/Sim800l" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SoftwareSerial" "/Users/paulpenney/Documents/Arduino/libraries/Sim800l/Sim800l.cpp" -o "/dev/null"
"/Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=160000000L -DLWIP_OPEN_SRC   -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SoftwareSerial" "-I/Users/paulpenney/Documents/Arduino/libraries/Sim800l" "/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SoftwareSerial/SoftwareSerial.cpp" -o "/dev/null"
"/Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=160000000L -DLWIP_OPEN_SRC   -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "-I/Users/paulpenney/Documents/Arduino/libraries/Sim800l" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SoftwareSerial" "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/sketch/readSms.ino.cpp" -o "/dev/null"
"/Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=160000000L -DLWIP_OPEN_SRC   -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "-I/Users/paulpenney/Documents/Arduino/libraries/Sim800l" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SoftwareSerial" "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/sketch/readSms.ino.cpp" -o "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
"/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino10/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
"/Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/include" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/tools/sdk/lwip/include" "-I/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=160000000L -DLWIP_OPEN_SRC   -DARDUINO=10609 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/variants/nodemcu" "-I/Users/paulpenney/Documents/Arduino/libraries/Sim800l" "-I/Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SoftwareSerial" "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/sketch/readSms.ino.cpp" -o "/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/sketch/readSms.ino.cpp.o"
readSms:36: error: 'uint8_t index' redeclared as different kind of symbol
 uint8_t index;   // to indicate the message to read.
         ^
In file included from /Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/stdlib.h:11:0,
                 from /Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/cores/esp8266/Arduino.h:27,
                 from /var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/build06e5add411000dfcbd3a1189688005ff.tmp/sketch/readSms.ino.cpp:1:
/Users/paulpenney/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/string.h:55:8: error: previous declaration of 'char* index(const char*, int)'
 char  *_EXFUN(index,(const char *, int));
        ^
/var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/arduino_modified_sketch_910342/readSms.ino: In function 'void setup()':
readSms:43: error: invalid conversion from 'char* (*)(const char*, int)' to 'uint8_t {aka unsigned char}' [-fpermissive]
  text=Sim800l.readSms(index);    
                            ^
In file included from /var/folders/7m/6kjjn06d4bq5s_fw_g38shhc0000gp/T/arduino_modified_sketch_910342/readSms.ino:32:0:
/Users/paulpenney/Documents/Arduino/libraries/Sim800l/Sim800l.h:70:9: error:   initializing argument 1 of 'String Sim800l::readSms(uint8_t)' [-fpermissive]
  String readSms(uint8_t index); //return all the content of sms
         ^
Using library Sim800l in folder: /Users/paulpenney/Documents/Arduino/libraries/Sim800l (legacy)
Using library SoftwareSerial at version 1.0 in folder: /Users/paulpenney/Library/Arduino15/packages/esp8266/hardware/esp8266/2.3.0/libraries/SoftwareSerial 
exit status 1
'uint8_t index' redeclared as different kind of symbol

//

**Comment by cristiansteib** [comment]
hello, please first try with another version of the IDE, the library is working good for many people.

**Comment by paulpenney** [comment]
Thanks, solved my problem.

**Comment by cristiansteib** [comment]
@paulpenney what did you do to solve?
