### ISSUE TITLE
Not sending SMS while moving

### ISSUE THREAD

**Issue by jLynx** [cristiansteib/Sim800l#12]
Hi I am having a problem where I can send a SMS to the device and have it send me another SMS back. This works fine while stationary(takes about 10-30 seconds to get a reply). But when I put it in my car and start driving and then send it a SMS to respond to, it doesn't send a reply right away, it takes about 2-10 minutes to reply to a single text. If I send it 2 in a row while moving it seems to reply within the normal 10-30 seconds but it only replies once, not twice (as I sent 2 text messages)
Do you have any idea why this is happening? I have tested this on 3 other modules and I am having the save problem.

P.S I am not using the reset pin, but this shouldn't have anything to do with it, should it?

**Comment by cristiansteib** [comment]
hello buddy. Maybe the problem is the bearerProfile, try to activate when is moving, or try to deactivate it using the functions :  activateBearerProfile(); or deactivateBearerProfile(); 
i don't think that the problem is the reset pin.

**Comment by DarkN3ss61** [comment]
@cristiansteib doesnt activateBearerProfile and deactivateBearerProfile only get called in updateRtc? Because i'm not calling that.

**Comment by cristiansteib** [comment]
yes, is used for establish communication with the tower.. so, try to activate and use with this configuration activated, just to see if  behavior change

**Comment by DarkN3ss61** [comment]
[Sim800l-1.5.0.zip](https://github.com/cristiansteib/Sim800l/files/621035/Sim800l-1.5.0.zip)
I got it working. I think it was the delay 100ms that was in the send SMS. I changed that to _buffer=_readSerial(); then it seemed to work no problem. Also I added a few other things into it like deleting a single SMS etc

**Comment by cristiansteib** [comment]
Perfect, i will going to see more deep the behavior of sms.. thanks !

**Comment by DarkN3ss61** [comment]
Opps, scratch that. It made it better but still happens when I'm going 100kmh. Works fine around 50kmh now though

**Comment by jLynx** [comment]
I feel like this could have been a power issue. I'll close this now.

**Comment by cristiansteib** [comment]
> I feel like this could have been a power issue. I'll close this now.

The problem is solved for you?

**Comment by jLynx** [comment]
Kind of. But I have been messing with the sim 800 models for a few years now (even made a site out of the https://temp-sms.org) and I know that power is a big issue with these. They need to have the exact voltage and enough amps to handle them or you will have a bad time. Before I was just powering it with 5v over usb. And that would have been the issue. I cannot confirm and the project I was working on with this issue no longer exists, so can't test there. But I am sure it's a power issue.
